services:
  mediamtx:
    build: .
    container_name: mediamtx
    restart: always
    ports:
      - "${MEDIAMTX_RTSP_PORT}:8554"     # RTSP input
      - "${MEDIAMTX_RTMP_PORT}:1935"     # RTMP server
      - "${MEDIAMTX_HTTP_STATS_PORT}:8888"     # HTTP (stats UI)
      - "8890:8889"     # WebRTC HTTP
      - "${MEDIAMTX_HTTP_API_PORT}:9997"     # HTTP API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    environment:
      - TZ=UTC
    networks:
      - rtsp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9997/v3/paths/list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rtsp-api:
    build: ./rtsp-api
    container_name: rtsp-api
    user: root  # Run as root to access Docker socket
    restart: always
    ports:
      - "${RTSP_API_PORT}:3002"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mediamtx
    env_file:
      - ./rtsp-api/.env
    networks:
      - rtsp-network

  rtsp-ui:
    build:
      context: ./rtsp-ui
      dockerfile: Dockerfile
      target: production
    container_name: rtsp-ui
    restart: always
    ports:
      - "${RTSP_UI_PORT}:3000"
    depends_on:
      - rtsp-api
    env_file:
      - ./rtsp-ui/.env
    networks:
      - rtsp-network

networks:
  rtsp-network:
